ALTER TABLE users ADD COLUMN referred_by INTEGER NULL;
ALTER TABLE users ADD COLUMN referral_bonus_granted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN referral_bonus_days INTEGER NOT NULL DEFAULT 0;
